### ISSUE TITLE
[1.12.2][Feature Request] Whitelist to Blacklist

### ISSUE THREAD

**Issue by Krutoy242** [mactso/HarderBranchMining#10]
Please add option to turn upside-down option of Whitelist to Blacklist.

Im using HBM in modpack [E2E-E](https://github.com/Krutoy242/Enigmatica2Expert-Extended).
Harder Branch Mining works incorrectly there - `Depth Dig Speed Modifier` option always slows dig speed x10 times, no matter of value, except `1.0`. Also, `Down Speed Modifier` option wont work without previous one.

But since there was no updates for 1.12, i would like if you add one simple option to turn Whitelist to Blacklist, so i can easily add stone to Blacklist so every other block would be easily mined.

P.S. For 1.12.2 version - HBM downloads is 80% from my modpack, lol.

**Comment by mactso** [comment]
Glad to hear you are enjoying it. 

I'll try to fix the math with the fix from later versions.

I'll estimate how hard reversing the omission list is and give you an update later today.

**Comment by mactso** [comment]
Okay, I have the HBM 1.12.2 environment set up.  Going to dig into it.

**Comment by mactso** [comment]
Okay... so it's built and the bugs are fixed.  Now I'm looking into the include list...

Here is an example:

    # Include Blocks: Mod:Block.  If populated, ONLY these blocks are slowed.
    S:"include Blocks : Mod: Block" <
        minecraft:stone  (<- works)
        minecraft:gravel (<-works but ignored because a soft block)
        minecraft:granite (<- prints error because "granite" was "stone"  (stone:4 or something like that)
        minecraft:geranite (<- prints error because it's misspelled)
     >

**Comment by mactso** [comment]
Note that the math bugs are fixed.  You may need to adjust the general dig speed and down speed to feel like you want.

**With the defaults**
Diamond isn't too bad down deep but is slower.
Iron is noticeably slower
Stone is kinda painful.
Wood is insanely slow.

I've added a command /harderbranchmining info | debug # 
_**info**_ prints useful info to the screen 
**_debug_** sets the debug level to 0,1,2 (or 0 if you type something goofy)

**Comment by mactso** [comment]
Testing now... expect to promote some time today.

**Comment by mactso** [comment]
The modid is now hbm2 to prevent a collision with another mod (nuclear tech which is hbm for some reason!?!?) and so the configuration file is now named hbm2.cfg.

**Comment by mactso** [comment]
let me know if you see any issues.  I'm also open to simple feature requests while the environment is set up.  
I won't be able to do anything with data tags (stone:0, stone:1 type of stuff).

**Comment by mactso** [comment]
Also dig speed modifier and downspeed modifier should be independent from each other now.

**Comment by Krutoy242** [comment]
Sounds good! I'm gonna test it today.

Oh, you didn't updated CF release yet, i though i could download it to test already 😅

**Comment by mactso** [comment]
It is updated.  It doesn't show on the main page because it's not a recent version.  Look in the FILES section.
It's approved and has 8 downloads.
https://www.curseforge.com/minecraft/mc-mods/harder-branch-mining/files

**Comment by Krutoy242** [comment]
Ok, thanks, gonna test it later then.

**Comment by Krutoy242** [comment]
It feels like i already reported it, but in Draconic Evolution's chestplate (that give creative flight), when i jump, HBM not working

https://user-images.githubusercontent.com/936618/197037433-d1484b9e-0edb-46b6-9f8d-b423303c9aee.mp4

**Comment by mactso** [comment]
Is it acting like it is in creative mode?  I wonder if draconic is using creative flight in some way and that's confusing it.
Please let me know.

**Comment by Krutoy242** [comment]
> like it is in creative mode

Yes, this chestplate give you creative flight.

**Comment by Krutoy242** [comment]
Since In my modpack when you reach Draconic Chest no one would use manual mining, i would ignore this issue.

So, since `whitelist` feature added and works fine, i could close current issue.

**Comment by mactso** [comment]
Thanks for your engagement on this issue!   I might do some more 1.12.2 updates while I'm fresh on it.
