### ISSUE TITLE
[1.12] Wrong information and unable to config

### ISSUE THREAD

**Issue by Krutoy242** [mactso/HarderBranchMining#11]
New version of HBM have few issues:
- Unable to change configs from game
- Wrong version number
- No mod description

![image](https://user-images.githubusercontent.com/936618/196899402-be8bfc41-8c7d-4f99-91ea-525bd8a8a47b.png)

**Comment by mactso** [comment]
Dang.  I'll look into that now.

**Comment by mactso** [comment]
Okay, I found the reason for this and I'll be submitting a fix shortly.  There is a file (mod.info) that isn't used any more that I had to update.

**Comment by mactso** [comment]
This has been submitted for approval.  Please let me know how it works out.

**Comment by Krutoy242** [comment]
Its fixed, but now HBM uses `hbm.cfg` again instead of `hbm2.cfg` as in previous version.

**Comment by Krutoy242** [comment]
Also, Debug Level always working like maximum `2` and can't be disabled:

https://user-images.githubusercontent.com/936618/197328550-a775a9db-be42-4246-b848-14a977167a76.mp4

**Comment by mactso** [comment]
That's odd about the debugging.  I didn't notice debugging messages.  I'll look at that immediately.

**Comment by mactso** [comment]
Okay found and fixed.  Testing it now.

**Comment by mactso** [comment]
I've finish testing it and submitted it for approval.
It's odd- I *literally* couldn't "see" the debugging statement on the screen during testing.   Guess I was tired.

**Comment by Krutoy242** [comment]
Installed and tested. Seems like everything working fine now, thanks!
