### ISSUE TITLE
v2.0.0.16 How do you turn off the message on the HUD

### ISSUE THREAD

**Issue by toastonrye** [mactso/HarderBranchMining#12]
I'm positive the message constantly under my minimap "harder branch mining 100%" wasn't always there. How do you turn it off?
I can't find any settings or hotkeys?

**Comment by toastonrye** [comment]
![image](https://user-images.githubusercontent.com/26075330/213840752-b609a86f-8e26-4d45-af36-487fa350a9dd.png)
User error, my bad! It's not related to this mod at all, it's a custom stage from FTB Quests and I accidentally pinned it.

**Comment by mactso** [comment]
Thanks for following up - that would have been confusing.
