### ISSUE TITLE
Mod is unavailable on Third-party Launchers

### ISSUE THREAD

**Issue by DDriggs00** [mactso/HarderBranchMining#14]
You have the Curseforge "Prevent Third-Party Distribution" setting enabled, which prevents your mod from being used on third-party launchers. Many people do not want to use the Overwolf launcher due to privacy and data-harvesting concerns, or inaccessibility on Linux, and this restriction makes it difficult for those people to use modpacks with your mod in them, as well as discouraging pack developers from including your mod. Additionally, it makes it much more difficult to host a server with this mod. For more details, see https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

I'm assuming this is unintentional since your mod is under the MIT License.

**Comment by mactso** [comment]
That's correct.  Some of our mods are available freely everywhere.   Some are available with user support.

While we are fine with 3rd party sites hosting their own copies and paying for their own bandwidth (a la the MIT license) those that use curseforge storage and bandwidth are destructive to the modding environment we depend on.

We plan to make mods available on 3rd party sites who share advertising (such as Modrinth) with authors and who maintain their own copies and use their own bandwidth and we also make mods available if they are pro-bono (like Spider Pig for people with arachnophobia) or they have user support through patreon.
