### ISSUE TITLE
Suggestion for a dimension whitelist/blacklist

### ISSUE THREAD

**Issue by SissyTrashQueen** [mactso/HarderBranchMining#2]
Just that. Thank you for your mod and time <3

**Comment by mactso** [comment]
Thanks!   I'll look into it and give you an update by next tuesday.

**Comment by mactso** [comment]
This concept is implemented in both 1.12.2 and 1.15 now.
You can individually configure tools by dimension.
If you don't configure a tool for a dimension, it falls back to the value for dimension 0.
If you don't configure a tool for dimension 0, it falls back to hbm:default:0 which has a default value of 10.

So if you want to whitelist a tool, set it up as exhaustion 0 for that dimension or the overworld.

Cheers!
