### ISSUE TITLE
Jumping in Draconic Evolution's Chestplate ignore slowness

### ISSUE THREAD

**Issue by Krutoy242** [mactso/HarderBranchMining#5]
When mining blocks, if i **jump** or fly in Draconic Chestplate, mining ignores slowness added by HBM.
Also, this happens when just jumping.
This not happens when i fly by other mod's creative flight providers.
Expecting slowness persist even when jumping or flying.

Demonstration video:
https://imgur.com/drUj5Yl

**MC**: 1.12.2
**HBM**: 2.0.0.8

**Comment by mactso** [comment]
Okay, thank you for the heads up!

This appears to be happening inside that mod.  Somehow that's preventing me from getting the events to modify them.

**Comment by Krutoy242** [comment]
So, this behavior would persist constantly?

**Comment by mactso** [comment]
Unfortunately it looks like it at the time. 
I'm sorry.  I can't see a way to stop it right now.
Normally when you are flying or underwater, your mining is slowed down so I guess he put something in to override that normal behavior and it's also blocking me.

Hmmm.   I just thought right now that I might be able to lower my event priority-- Right now it's default (normal).  Maybe I can come in after he's done and slow it back down.  I'll give that a look tomorrow.

Please confirm you are using 
Draconic-Evolution-1.12.2-2.3.25.351-universal
at
"https://www.curseforge.com/minecraft/mc-mods/draconic-evolution/files/2867186"

**Comment by Krutoy242** [comment]
Thank you!
Yes, im using version you linked.

**Comment by mactso** [comment]
Okay, have this in the debugger and he's completely bypassing the normal digging events.

PlayerEvent.BreakSpeed shows the speed drops from 8 to 1.6 when in the air.  
HBM correctly slows that digging speed down further to from 1.6 to 1.02.   

But then instead, even a stone pickaxe digs quickly when I'm wearing the draconic breastplate and flying.

I'm sorry but I don't see a way to fix this.   

HBM should still work in the game/pack until you get to the point where you are using draconic tools.
