### ISSUE TITLE
Crash on the newest Forge version 1.16.1

### ISSUE THREAD

**Issue by Kroko1337** [mactso/HarderBranchMining#6]
https://pastebin.com/rxEqYW6y

**Comment by nepphhh** [comment]
Seconded. Will not load in. 
![2020-07-29_18 39 24](https://user-images.githubusercontent.com/4913409/88862255-cad9e580-d1cd-11ea-8b9e-aebc33fc0636.png)

**Comment by mactso** [comment]
Please use the most current version of harder branch mining.
Forged changed the way commands are registered.

If the issue is still recurring, please reopen the issue with...

Minecraft Version: 1.16.1/1.15.1/1.15.2 etc.
Forge Version: 32.0.??
Harder Branch Mining Version: 1.0.0.?
