### ISSUE TITLE
Breaking blocks with high efficiency on a server at lower levels causes rubber banding

### ISSUE THREAD

**Issue by Accia121** [mactso/HarderBranchMining#7]
I've singled it down to this mod being the issue through individual testing of suspect mods. (1.16.4 - forge 35.1.29)
When breaking blocks with high efficiency at lower levels the blocks break then replace (similar to blocks rubber banding on a server - which may be related)
This only occurs on the server below the speed modifier level (when it starts to alter the dig speed) although it is not straight away but rather 10-20 blocks below this level.
- Using an efficiency V diamond pickaxe
- blocks being broken are netherrack
other blocks break and remain for a few seconds before breaking and dropping the item
https://imgur.com/a/GYu8BE6
Here is a video before removing other mods (however the effect is the same after removing other mods)
[CONFIG FILE] - 
[harderbranchmining-common.txt](https://github.com/mactso/HarderBranchMining/files/5843454/harderbranchmining-common.txt)

Changing the dig speed to 1.0 does remove this issue but also stops me from using this feature altogether

If you need me to do any other tests / give any other info just ask

**Comment by mactso** [comment]
I'll give this a look soon when I validate the mob for 1.16.5.

Is this single player?

What is the Y altitude this is occurring at?

It sounds like the calculated time on the server and the client are out of sync.  This could be due to different configuration file values.

The client can tell the server what ever it wants and display that to the player but the server enforces the actual breaking of the block.

I'll test both scenarios.

Cheers!  MacTso

**Comment by mactso** [comment]
okay, testing this on the server now.  will see what happens.

**Comment by mactso** [comment]
Hi there!  Okay, it tests clean under client/server.   I suspect that 

1) the client and server are out of sync (so delete both configuration files and let the mod recreate them)
2) then restore any changes one by one to both.

I tested this with diamond ef5, netherite ef5
those + haste.
those + beacon.

None of these test cases duplicated the behavior in the example video.

The only other thing I can think of is that there is some other mod?  

You might try the new version-- it's universal for all version 16 (1.16.1-1.16.5) now.

If you continue to see the errors  and can give a bit more information (modlist, Y altitude) I can take another look at it.

While testing I had an idea for how to make a less flexible but more robust version that might run on the server side only.  I'll probably write and upload it later this week.  It will be something like "HarderBranchMining Lite".

Cheers!  
Mactso
